steps:
# Install dependencies
- name: node
  entrypoint: npm
  args: ['install']
# Docker build
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/stubbed-service', '.' ]
# Push new image to Google Cloud
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['push', 'gcr.io/$PROJECT_ID/stubbed-service']
images:
- gcr.io/${PROJECT_ID}/stubbed-service

# Run tests
#- name: node
#  entrypoint: npm
#  args: ['test']
# Run custom commands
#- name: node
#  entrypoint: npm
#  args: ['run', 'build']
# [END cloudbuild_npm_node]
